# Generated by Django 6.0.3 on 2026-04-06 15:56

import applications.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="company name"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="job title"
                    ),
                ),
                (
                    "job_url",
                    models.URLField(
                        blank=True, default="", verbose_name="job posting URL"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="location"
                    ),
                ),
                (
                    "work_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                            ("on_site", "On-site"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="work mode",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("saved", "Saved"),
                            ("applied", "Applied"),
                            ("screening", "Screening"),
                            ("interview", "Interview"),
                            ("offer", "Offer"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="saved",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "salary_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="salary min (annual)"
                    ),
                ),
                (
                    "salary_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="salary max (annual)"
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("indeed", "Indeed"),
                            ("company", "Company Website"),
                            ("referral", "Referral"),
                            ("recruiter", "Recruiter"),
                            ("job_board", "Job Board"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="source",
                    ),
                ),
                (
                    "source_detail",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="E.g. referrer name, recruiter company, specific job board.",
                        max_length=200,
                        verbose_name="source detail",
                    ),
                ),
                (
                    "applied_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date applied"
                    ),
                ),
                (
                    "interview_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="interview date/time"
                    ),
                ),
                (
                    "offer_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="offer deadline"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "job application",
                "verbose_name_plural": "job applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("cv", "CV / Resume"),
                            ("cover_letter", "Cover Letter"),
                            ("other", "Other"),
                        ],
                        default="cv",
                        max_length=20,
                        verbose_name="document type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=applications.models.cv_upload_path,
                        validators=[
                            applications.models.validate_cv_extension,
                            applications.models.validate_cv_size,
                        ],
                        verbose_name="file",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="original filename"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="applications.jobapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("saved", "Saved"),
                            ("applied", "Applied"),
                            ("screening", "Screening"),
                            ("interview", "Interview"),
                            ("offer", "Offer"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="from status",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("saved", "Saved"),
                            ("applied", "Applied"),
                            ("screening", "Screening"),
                            ("interview", "Interview"),
                            ("offer", "Offer"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=20,
                        verbose_name="to status",
                    ),
                ),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional note about why the status changed.",
                        max_length=500,
                        verbose_name="note",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="applications.jobapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "status history",
                "verbose_name_plural": "status histories",
                "ordering": ["changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["user", "status"], name="application_user_id_16fc9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["user", "created_at"], name="application_user_id_93ab22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["user", "applied_date"], name="application_user_id_42b6ac_idx"
            ),
        ),
    ]
