services:
  # PostgreSQL
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: job_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Django API
  api:
    build: .
    command: >
      sh -c "python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - media_data:/app/media 
    ports:
      - "8000:8000"
    env_file:
      - .env 
    environment:
      DJANGO_SETTINGS_MODULE: jobtracker.settings.dev
      DATABASE_URL: postgres://postgres:password@db:5432/job_tracker_db
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  # Celery Worker
  celery_worker:
    build: .
    command: celery -A jobtracker worker -l info -Q default,reminders
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: jobtracker.settings.dev
      DATABASE_URL: postgres://postgres:password@db:5432/job_tracker_db
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      - api
      - redis


  # Celery Beat
  celery_beat:
    build: .
    command: >
      celery -A jobtracker beat -l info
      --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: jobtracker.settings.dev
      DATABASE_URL: postgres://postgres:password@db:5432/job_tracker_db
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - api
      - redis
 
volumes:
  postgres_data:
  media_data: