# Generated by Django 6.0.3 on 2026-04-06 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("follow_up", "Follow Up"),
                            ("interview_prep", "Interview Prep"),
                            ("deadline", "Deadline"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="reminder type",
                    ),
                ),
                (
                    "remind_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Exact date and time to send the reminder email (UTC).",
                        verbose_name="remind at",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional note to include in the reminder email.",
                        verbose_name="message",
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="sent"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Uncheck to cancel this reminder without deleting it.",
                        verbose_name="active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="applications.jobapplication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "reminder",
                "verbose_name_plural": "reminders",
                "ordering": ["remind_at"],
                "indexes": [
                    models.Index(
                        fields=["is_sent", "is_active", "remind_at"],
                        name="reminders_due_idx",
                    )
                ],
            },
        ),
    ]
