/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analytics/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Main dashboard summary
         * @description Returns all key metrics in a single call. Designed for the main dashboard to avoid multiple round-trips.
         */
        get: operations["v1_analytics_dashboard_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/funnel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stage conversion funnel
         * @description For each pipeline stage, returns the count and percentage of applications that ever reached that stage (including those that have since moved on or been rejected).
         */
        get: operations["v1_analytics_funnel_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/heatmap/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily application activity (heatmap data)
         * @description Returns one entry per day for the last 365 days. Days with zero activity are included so the frontend can render a full heatmap grid.
         */
        get: operations["v1_analytics_heatmap_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/response-rate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Response, interview, and offer rates
         * @description response_rate: % of applications that moved past 'applied'. interview_rate: % that reached interview stage. offer_rate: % that received an offer.
         */
        get: operations["v1_analytics_response_rate_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/sources/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Applications by discovery source
         * @description Only sources with at least one application are returned, sorted by count descending.
         */
        get: operations["v1_analytics_sources_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/stage-duration/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Average days between pipeline stages
         * @description Computed from StatusHistory entries. Only transitions with at least one data point are returned. sample_size tells you how many transitions the average is based on.
         */
        get: operations["v1_analytics_stage_duration_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Application count per status
         * @description Returns all pipeline statuses with their application count. Zero counts are included.
         */
        get: operations["v1_analytics_status_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/top-companies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Most applied-to companies
         * @description Shared base for all analytics views.
         *     Provides a scoped queryset: own applications for job seekers,
         *     all applications for admins.
         *     Accepts an optional ?user_id= query param for admins to scope to one user.
         */
        get: operations["v1_analytics_top_companies_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/volume/monthly/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Monthly application volume
         * @description Shared base for all analytics views.
         *     Provides a scoped queryset: own applications for job seekers,
         *     all applications for admins.
         *     Accepts an optional ?user_id= query param for admins to scope to one user.
         */
        get: operations["v1_analytics_volume_monthly_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/volume/weekly/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Weekly application volume
         * @description Shared base for all analytics views.
         *     Provides a scoped queryset: own applications for job seekers,
         *     all applications for admins.
         *     Accepts an optional ?user_id= query param for admins to scope to one user.
         */
        get: operations["v1_analytics_volume_weekly_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List job applications
         * @description Full CRUD for job applications.
         *     Users only ever see and modify their own applications.
         *     Admins can see all (scoped in get_queryset).
         */
        get: operations["v1_applications_list"];
        put?: never;
        /**
         * Create a new application
         * @description Full CRUD for job applications.
         *     Users only ever see and modify their own applications.
         *     Admins can see all (scoped in get_queryset).
         */
        post: operations["v1_applications_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve application detail
         * @description Full CRUD for job applications.
         *     Users only ever see and modify their own applications.
         *     Admins can see all (scoped in get_queryset).
         */
        get: operations["v1_applications_retrieve"];
        /**
         * Full update
         * @description Full CRUD for job applications.
         *     Users only ever see and modify their own applications.
         *     Admins can see all (scoped in get_queryset).
         */
        put: operations["v1_applications_update"];
        post?: never;
        /**
         * Delete an application
         * @description Full CRUD for job applications.
         *     Users only ever see and modify their own applications.
         *     Admins can see all (scoped in get_queryset).
         */
        delete: operations["v1_applications_destroy"];
        options?: never;
        head?: never;
        /**
         * Partial update (status change, notes, etc.)
         * @description Full CRUD for job applications.
         *     Users only ever see and modify their own applications.
         *     Admins can see all (scoped in get_queryset).
         */
        patch: operations["v1_applications_partial_update"];
        trace?: never;
    };
    "/api/v1/applications/{id}/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a document (CV, cover letter) to an application
         * @description Full CRUD for job applications.
         *     Users only ever see and modify their own applications.
         *     Admins can see all (scoped in get_queryset).
         */
        post: operations["v1_applications_documents_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{id}/documents/{doc_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a document from an application
         * @description Full CRUD for job applications.
         *     Users only ever see and modify their own applications.
         *     Admins can see all (scoped in get_queryset).
         */
        delete: operations["v1_applications_documents_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{id}/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get status change history for an application
         * @description Full CRUD for job applications.
         *     Users only ever see and modify their own applications.
         *     Admins can see all (scoped in get_queryset).
         */
        get: operations["v1_applications_history_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Authenticate with email + password.
         *     Returns access token, refresh token, and basic user info.
         */
        post: operations["v1_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Invalidate the provided refresh token by adding it to the blacklist.
         *     The access token will expire naturally (short-lived by design).
         */
        post: operations["v1_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get own profile
         * @description GET  — return the authenticated user's full profile.
         *     PATCH — partial update (preferred for frontend).
         *     PUT  — full update.
         *     Avatar upload via multipart/form-data.
         */
        get: operations["v1_auth_me_retrieve"];
        /**
         * Replace own profile
         * @description GET  — return the authenticated user's full profile.
         *     PATCH — partial update (preferred for frontend).
         *     PUT  — full update.
         *     Avatar upload via multipart/form-data.
         */
        put: operations["v1_auth_me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update own profile
         * @description GET  — return the authenticated user's full profile.
         *     PATCH — partial update (preferred for frontend).
         *     PUT  — full update.
         *     Avatar upload via multipart/form-data.
         */
        patch: operations["v1_auth_me_partial_update"];
        trace?: never;
    };
    "/api/v1/auth/me/password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change own password
         * @description Change the authenticated user's password.
         *     Requires the current password for verification.
         *     After a successful change, all existing tokens remain valid until they expire
         *     — consider logging the user out on the frontend after this call.
         */
        post: operations["v1_auth_me_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Register a new Job Seeker account.
         *     No authentication required.
         *     Returns the created user profile (no tokens — user must login separately).
         */
        post: operations["v1_auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Refresh an expired access token using a valid refresh token. */
        post: operations["v1_auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all users (admin only)
         * @description Returns a paginated list of all users.
         *     Restricted to Admin role only.
         */
        get: operations["v1_auth_users_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List reminders
         * @description CRUD for reminders.
         *     Scoped to the authenticated user's own reminders.
         */
        get: operations["v1_reminders_list"];
        put?: never;
        /**
         * Create a reminder
         * @description CRUD for reminders.
         *     Scoped to the authenticated user's own reminders.
         */
        post: operations["v1_reminders_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a reminder
         * @description CRUD for reminders.
         *     Scoped to the authenticated user's own reminders.
         */
        get: operations["v1_reminders_retrieve"];
        /**
         * Full update
         * @description CRUD for reminders.
         *     Scoped to the authenticated user's own reminders.
         */
        put: operations["v1_reminders_update"];
        post?: never;
        /**
         * Delete a reminder
         * @description CRUD for reminders.
         *     Scoped to the authenticated user's own reminders.
         */
        delete: operations["v1_reminders_destroy"];
        options?: never;
        head?: never;
        /**
         * Partial update (reschedule, cancel)
         * @description CRUD for reminders.
         *     Scoped to the authenticated user's own reminders.
         */
        patch: operations["v1_reminders_partial_update"];
        trace?: never;
    };
    "/api/v1/reminders/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a reminder (sets is_active=False)
         * @description Convenience endpoint to deactivate a reminder without deleting it.
         *     Useful for frontend 'Cancel reminder' buttons — no request body needed.
         */
        post: operations["v1_reminders_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        BlankEnum: "";
        ConversionFunnelItem: {
            stage: string;
            label: string;
            count: number;
            /**
             * Format: double
             * @description % of total applications that reached this stage
             */
            rate: number;
        };
        /**
         * @description Extends the default JWT login response to include basic user info,
         *     so the frontend doesn't need an extra /me call right after login.
         */
        CustomTokenObtainPairRequest: {
            email: string;
            password: string;
        };
        DashboardSummary: {
            total_applications: number;
            active_applications: number;
            status_breakdown: components["schemas"]["StatusBreakdownItem"][];
            response_rate: components["schemas"]["ResponseRate"];
            weekly_volume: components["schemas"]["WeeklyVolumeItem"][];
            source_breakdown: components["schemas"]["SourceBreakdownItem"][];
            conversion_funnel: components["schemas"]["ConversionFunnelItem"][];
            top_companies: components["schemas"]["TopCompany"][];
        };
        Document: {
            /** Format: uuid */
            readonly id: string;
            document_type?: components["schemas"]["DocumentTypeEnum"];
            /** Format: uri */
            file: string;
            readonly file_url: string;
            readonly original_filename: string;
            readonly file_size_display: string;
            /** Format: date-time */
            readonly uploaded_at: string;
        };
        DocumentRequest: {
            document_type?: components["schemas"]["DocumentTypeEnum"];
            /** Format: binary */
            file: string;
        };
        /**
         * @description * `cv` - CV / Resume
         *     * `cover_letter` - Cover Letter
         *     * `other` - Other
         * @enum {string}
         */
        DocumentTypeEnum: "cv" | "cover_letter" | "other";
        HeatmapDay: {
            /** Format: date */
            date: string;
            count: number;
        };
        /** @description Full detail view including nested documents and status history. */
        JobApplicationDetail: {
            /** Format: uuid */
            readonly id: string;
            readonly company_name: string;
            readonly job_title: string;
            readonly location: string;
            readonly work_mode: components["schemas"]["WorkModeEnum"];
            readonly work_mode_display: string;
            readonly status: components["schemas"]["ToStatusEnum"];
            readonly status_display: string;
            readonly salary_range: string;
            readonly source: components["schemas"]["SourceEnum"];
            /**
             * Date applied
             * Format: date
             */
            readonly applied_date: string | null;
            /**
             * Interview date/time
             * Format: date-time
             */
            readonly interview_date: string | null;
            readonly document_count: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /**
             * Job posting URL
             * Format: uri
             */
            job_url?: string;
            /** Salary min (annual) */
            salary_min?: number | null;
            /** Salary max (annual) */
            salary_max?: number | null;
            /** Currency */
            salary_currency?: string;
            /** Format: date */
            offer_deadline?: string | null;
            /** @description E.g. referrer name, recruiter company, specific job board. */
            source_detail?: string;
            notes?: string;
            readonly documents: components["schemas"]["Document"][];
            readonly status_history: components["schemas"]["StatusHistory"][];
        };
        /**
         * @description Compact representation for paginated list views.
         *     Avoids N+1 by not including nested relations.
         *     Status display label included for frontend rendering.
         */
        JobApplicationList: {
            /** Format: uuid */
            readonly id: string;
            readonly company_name: string;
            readonly job_title: string;
            readonly location: string;
            readonly work_mode: components["schemas"]["WorkModeEnum"];
            readonly work_mode_display: string;
            readonly status: components["schemas"]["ToStatusEnum"];
            readonly status_display: string;
            readonly salary_range: string;
            readonly source: components["schemas"]["SourceEnum"];
            /**
             * Date applied
             * Format: date
             */
            readonly applied_date: string | null;
            /**
             * Interview date/time
             * Format: date-time
             */
            readonly interview_date: string | null;
            readonly document_count: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description Handles creation and updates.
         *     On status change, automatically writes a StatusHistory entry.
         *     User is injected from request.user — never from the payload.
         */
        JobApplicationWrite: {
            /** Format: uuid */
            readonly id: string;
            company_name: string;
            job_title: string;
            /**
             * Job posting URL
             * Format: uri
             */
            job_url?: string;
            location?: string;
            work_mode?: components["schemas"]["WorkModeEnum"] | components["schemas"]["BlankEnum"];
            status?: components["schemas"]["ToStatusEnum"];
            /** Salary min (annual) */
            salary_min?: number | null;
            /** Salary max (annual) */
            salary_max?: number | null;
            /** Currency */
            salary_currency?: string;
            source?: components["schemas"]["SourceEnum"];
            /** @description E.g. referrer name, recruiter company, specific job board. */
            source_detail?: string;
            /**
             * Date applied
             * Format: date
             */
            applied_date?: string | null;
            /**
             * Interview date/time
             * Format: date-time
             */
            interview_date?: string | null;
            /** Format: date */
            offer_deadline?: string | null;
            notes?: string;
        };
        /**
         * @description Handles creation and updates.
         *     On status change, automatically writes a StatusHistory entry.
         *     User is injected from request.user — never from the payload.
         */
        JobApplicationWriteRequest: {
            company_name: string;
            job_title: string;
            /**
             * Job posting URL
             * Format: uri
             */
            job_url?: string;
            location?: string;
            work_mode?: components["schemas"]["WorkModeEnum"] | components["schemas"]["BlankEnum"];
            status?: components["schemas"]["ToStatusEnum"];
            /** Salary min (annual) */
            salary_min?: number | null;
            /** Salary max (annual) */
            salary_max?: number | null;
            /** Currency */
            salary_currency?: string;
            source?: components["schemas"]["SourceEnum"];
            /** @description E.g. referrer name, recruiter company, specific job board. */
            source_detail?: string;
            /**
             * Date applied
             * Format: date
             */
            applied_date?: string | null;
            /**
             * Interview date/time
             * Format: date-time
             */
            interview_date?: string | null;
            /** Format: date */
            offer_deadline?: string | null;
            notes?: string;
        };
        MonthlyVolumeItem: {
            /** @description Month key, e.g. '2024-06' */
            month: string;
            /** @description Human-readable label, e.g. 'Jun 2024' */
            label: string;
            count: number;
        };
        PaginatedJobApplicationListList: {
            pagination?: {
                count?: number;
                total_pages?: number;
                current_page?: number;
                page_size?: number;
                has_next?: boolean;
                has_previous?: boolean;
                next?: string | null;
                previous?: string | null;
            };
            results?: components["schemas"]["JobApplicationList"][];
        };
        PaginatedReminderListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ReminderList"][];
        };
        PaginatedStatusHistoryList: {
            pagination?: {
                count?: number;
                total_pages?: number;
                current_page?: number;
                page_size?: number;
                has_next?: boolean;
                has_previous?: boolean;
                next?: string | null;
                previous?: string | null;
            };
            results?: components["schemas"]["StatusHistory"][];
        };
        PaginatedUserPublicList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["UserPublic"][];
        };
        /**
         * @description Handles creation and updates.
         *     On status change, automatically writes a StatusHistory entry.
         *     User is injected from request.user — never from the payload.
         */
        PatchedJobApplicationWriteRequest: {
            company_name?: string;
            job_title?: string;
            /**
             * Job posting URL
             * Format: uri
             */
            job_url?: string;
            location?: string;
            work_mode?: components["schemas"]["WorkModeEnum"] | components["schemas"]["BlankEnum"];
            status?: components["schemas"]["ToStatusEnum"];
            /** Salary min (annual) */
            salary_min?: number | null;
            /** Salary max (annual) */
            salary_max?: number | null;
            /** Currency */
            salary_currency?: string;
            source?: components["schemas"]["SourceEnum"];
            /** @description E.g. referrer name, recruiter company, specific job board. */
            source_detail?: string;
            /**
             * Date applied
             * Format: date
             */
            applied_date?: string | null;
            /**
             * Interview date/time
             * Format: date-time
             */
            interview_date?: string | null;
            /** Format: date */
            offer_deadline?: string | null;
            notes?: string;
        };
        /**
         * @description Handles reminder creation and updates.
         *
         *     Validates:
         *     - remind_at must be in the future (on create)
         *     - application must belong to the requesting user
         *     - cannot edit a reminder that has already been sent
         */
        PatchedReminderWriteRequest: {
            /** Format: uuid */
            application?: string;
            reminder_type?: components["schemas"]["ReminderTypeEnum"];
            /**
             * Format: date-time
             * @description Exact date and time to send the reminder email (UTC).
             */
            remind_at?: string;
            /** @description Optional note to include in the reminder email. */
            message?: string;
            /**
             * Active
             * @description Uncheck to cancel this reminder without deleting it.
             */
            is_active?: boolean;
        };
        /**
         * @description Full profile for the authenticated user's own account.
         *     Readable + writable (except id, email, role, date_joined).
         *     Email changes are handled separately to allow re-verification in future.
         */
        PatchedUserProfileRequest: {
            first_name?: string;
            last_name?: string;
            bio?: string;
            location?: string;
            /** Format: uri */
            website?: string;
            /** Format: binary */
            avatar?: string | null;
        };
        /**
         * @description Handles new user sign-up.
         *     Requires password + password_confirm that must match.
         *     Returns the created user (without exposing the password hash).
         */
        Register: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Email address
             * Format: email
             */
            email: string;
            first_name: string;
            last_name: string;
        };
        /**
         * @description Handles new user sign-up.
         *     Requires password + password_confirm that must match.
         *     Returns the created user (without exposing the password hash).
         */
        RegisterRequest: {
            /**
             * Email address
             * Format: email
             */
            email: string;
            first_name: string;
            last_name: string;
            password: string;
            /** Confirm password */
            password_confirm: string;
        };
        /** @description Full detail with nested application summary. */
        ReminderDetail: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly application: string;
            readonly company_name: string;
            readonly job_title: string;
            readonly reminder_type: components["schemas"]["ReminderTypeEnum"];
            readonly reminder_type_display: string;
            /**
             * Format: date-time
             * @description Exact date and time to send the reminder email (UTC).
             */
            readonly remind_at: string;
            /** @description Optional note to include in the reminder email. */
            readonly message: string;
            /** Sent */
            readonly is_sent: boolean;
            /** Format: date-time */
            readonly sent_at: string | null;
            /**
             * Active
             * @description Uncheck to cancel this reminder without deleting it.
             */
            readonly is_active: boolean;
            readonly is_due: boolean;
            readonly is_overdue: boolean;
            /** Format: date-time */
            readonly created_at: string;
            readonly application_detail: components["schemas"]["JobApplicationList"];
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Compact read-only representation for list views. */
        ReminderList: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly application: string;
            readonly company_name: string;
            readonly job_title: string;
            readonly reminder_type: components["schemas"]["ReminderTypeEnum"];
            readonly reminder_type_display: string;
            /**
             * Format: date-time
             * @description Exact date and time to send the reminder email (UTC).
             */
            readonly remind_at: string;
            /** @description Optional note to include in the reminder email. */
            readonly message: string;
            /** Sent */
            readonly is_sent: boolean;
            /** Format: date-time */
            readonly sent_at: string | null;
            /**
             * Active
             * @description Uncheck to cancel this reminder without deleting it.
             */
            readonly is_active: boolean;
            readonly is_due: boolean;
            readonly is_overdue: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `follow_up` - Follow Up
         *     * `interview_prep` - Interview Prep
         *     * `deadline` - Deadline
         *     * `general` - General
         * @enum {string}
         */
        ReminderTypeEnum: "follow_up" | "interview_prep" | "deadline" | "general";
        /**
         * @description Handles reminder creation and updates.
         *
         *     Validates:
         *     - remind_at must be in the future (on create)
         *     - application must belong to the requesting user
         *     - cannot edit a reminder that has already been sent
         */
        ReminderWrite: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            application: string;
            reminder_type?: components["schemas"]["ReminderTypeEnum"];
            /**
             * Format: date-time
             * @description Exact date and time to send the reminder email (UTC).
             */
            remind_at: string;
            /** @description Optional note to include in the reminder email. */
            message?: string;
            /**
             * Active
             * @description Uncheck to cancel this reminder without deleting it.
             */
            is_active?: boolean;
        };
        /**
         * @description Handles reminder creation and updates.
         *
         *     Validates:
         *     - remind_at must be in the future (on create)
         *     - application must belong to the requesting user
         *     - cannot edit a reminder that has already been sent
         */
        ReminderWriteRequest: {
            /** Format: uuid */
            application: string;
            reminder_type?: components["schemas"]["ReminderTypeEnum"];
            /**
             * Format: date-time
             * @description Exact date and time to send the reminder email (UTC).
             */
            remind_at: string;
            /** @description Optional note to include in the reminder email. */
            message?: string;
            /**
             * Active
             * @description Uncheck to cancel this reminder without deleting it.
             */
            is_active?: boolean;
        };
        ResponseRate: {
            total: number;
            responded: number;
            /**
             * Format: double
             * @description % of applications that moved past 'applied'
             */
            response_rate: number;
            /**
             * Format: double
             * @description % of applications that reached interview
             */
            interview_rate: number;
            /**
             * Format: double
             * @description % of applications that received an offer
             */
            offer_rate: number;
        };
        /**
         * @description * `job_seeker` - Job Seeker
         *     * `admin` - Admin
         * @enum {string}
         */
        RoleEnum: "job_seeker" | "admin";
        SourceBreakdownItem: {
            source: string;
            label: string;
            count: number;
        };
        /**
         * @description * `linkedin` - LinkedIn
         *     * `indeed` - Indeed
         *     * `company` - Company Website
         *     * `referral` - Referral
         *     * `recruiter` - Recruiter
         *     * `job_board` - Job Board
         *     * `other` - Other
         * @enum {string}
         */
        SourceEnum: "linkedin" | "indeed" | "company" | "referral" | "recruiter" | "job_board" | "other";
        StageDurationItem: {
            from_stage: string;
            to_stage: string;
            /** @description e.g. 'Applied → Screening' */
            label: string;
            /** Format: double */
            avg_days: number;
            /** @description Number of transitions this average is based on */
            sample_size: number;
        };
        StatusBreakdownItem: {
            status: string;
            label: string;
            count: number;
        };
        StatusHistory: {
            /** Format: uuid */
            readonly id: string;
            readonly from_status: components["schemas"]["ToStatusEnum"];
            readonly from_status_display: string;
            readonly to_status: components["schemas"]["ToStatusEnum"];
            readonly to_status_display: string;
            /** Format: date-time */
            readonly changed_at: string;
            /** @description Optional note about why the status changed. */
            readonly note: string;
        };
        /**
         * @description * `saved` - Saved
         *     * `applied` - Applied
         *     * `screening` - Screening
         *     * `interview` - Interview
         *     * `offer` - Offer
         *     * `accepted` - Accepted
         *     * `rejected` - Rejected
         *     * `withdrawn` - Withdrawn
         * @enum {string}
         */
        ToStatusEnum: "saved" | "applied" | "screening" | "interview" | "offer" | "accepted" | "rejected" | "withdrawn";
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        TopCompany: {
            company_name: string;
            count: number;
        };
        /**
         * @description Full profile for the authenticated user's own account.
         *     Readable + writable (except id, email, role, date_joined).
         *     Email changes are handled separately to allow re-verification in future.
         */
        UserProfile: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            first_name: string;
            last_name: string;
            readonly full_name: string;
            readonly role: string;
            bio?: string;
            location?: string;
            /** Format: uri */
            website?: string;
            /** Format: uri */
            avatar?: string | null;
            readonly application_count: string;
            /** Format: date-time */
            readonly date_joined: string;
            /** Format: date-time */
            readonly last_login: string | null;
        };
        /**
         * @description Full profile for the authenticated user's own account.
         *     Readable + writable (except id, email, role, date_joined).
         *     Email changes are handled separately to allow re-verification in future.
         */
        UserProfileRequest: {
            first_name: string;
            last_name: string;
            bio?: string;
            location?: string;
            /** Format: uri */
            website?: string;
            /** Format: binary */
            avatar?: string | null;
        };
        /**
         * @description Minimal read-only representation — safe for admin user listings.
         *     Does not expose email or personal details of other users.
         */
        UserPublic: {
            /** Format: uuid */
            readonly id: string;
            readonly full_name: string;
            readonly role: components["schemas"]["RoleEnum"];
            /** Format: uri */
            readonly avatar: string | null;
            /** Format: date-time */
            readonly date_joined: string;
        };
        WeeklyVolumeItem: {
            /** @description ISO week label, e.g. '2024-W22' */
            week: string;
            count: number;
        };
        /**
         * @description * `remote` - Remote
         *     * `hybrid` - Hybrid
         *     * `on_site` - On-site
         * @enum {string}
         */
        WorkModeEnum: "remote" | "hybrid" | "on_site";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_analytics_dashboard_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    v1_analytics_funnel_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversionFunnelItem"][];
                };
            };
        };
    };
    v1_analytics_heatmap_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatmapDay"][];
                };
            };
        };
    };
    v1_analytics_response_rate_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseRate"];
                };
            };
        };
    };
    v1_analytics_sources_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceBreakdownItem"][];
                };
            };
        };
    };
    v1_analytics_stage_duration_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageDurationItem"][];
                };
            };
        };
    };
    v1_analytics_status_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusBreakdownItem"][];
                };
            };
        };
    };
    v1_analytics_top_companies_list: {
        parameters: {
            query?: {
                /** @description Max companies to return (default 10) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopCompany"][];
                };
            };
        };
    };
    v1_analytics_volume_monthly_list: {
        parameters: {
            query?: {
                /** @description Number of months to include (default 12, max 24) */
                months?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyVolumeItem"][];
                };
            };
        };
    };
    v1_analytics_volume_weekly_list: {
        parameters: {
            query?: {
                /** @description Number of weeks to include (default 12, max 52) */
                weeks?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyVolumeItem"][];
                };
            };
        };
    };
    v1_applications_list: {
        parameters: {
            query?: {
                /** @description Applied on or after (YYYY-MM-DD) */
                applied_after?: string;
                /** @description true = active only, false = terminal only */
                is_active?: string;
                /** @description Order by: created_at, applied_date, company_name, -created_at … */
                ordering?: string;
                /** @description Page number */
                page?: string;
                /** @description Results per page (max 100) */
                page_size?: string;
                /** @description Search company, title, location, notes */
                search?: string;
                /** @description Filter by status (repeatable) */
                status?: string;
                /** @description Filter by work mode */
                work_mode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedJobApplicationListList"];
                };
            };
        };
    };
    v1_applications_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobApplicationWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["JobApplicationWriteRequest"];
                "multipart/form-data": components["schemas"]["JobApplicationWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobApplicationWrite"];
                };
            };
        };
    };
    v1_applications_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobApplicationDetail"];
                };
            };
        };
    };
    v1_applications_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobApplicationWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["JobApplicationWriteRequest"];
                "multipart/form-data": components["schemas"]["JobApplicationWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobApplicationWrite"];
                };
            };
        };
    };
    v1_applications_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_applications_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedJobApplicationWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedJobApplicationWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedJobApplicationWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobApplicationWrite"];
                };
            };
        };
    };
    v1_applications_documents_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["DocumentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    v1_applications_documents_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_applications_history_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStatusHistoryList"];
                };
            };
        };
    };
    v1_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomTokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomTokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["CustomTokenObtainPairRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    refresh?: string;
                };
            };
        };
        responses: {
            /** @description Logout successful — refresh token blacklisted. */
            205: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or missing refresh token. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    v1_auth_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UserProfileRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserProfileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    v1_auth_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedUserProfileRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserProfileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    v1_auth_me_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
        };
    };
    v1_auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    v1_auth_users_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /**
                 * @description * `job_seeker` - Job Seeker
                 *     * `admin` - Admin
                 */
                role?: "admin" | "job_seeker";
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserPublicList"];
                };
            };
        };
    };
    v1_reminders_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedReminderListList"];
                };
            };
        };
    };
    v1_reminders_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ReminderWriteRequest"];
                "multipart/form-data": components["schemas"]["ReminderWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderWrite"];
                };
            };
        };
    };
    v1_reminders_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderDetail"];
                };
            };
        };
    };
    v1_reminders_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ReminderWriteRequest"];
                "multipart/form-data": components["schemas"]["ReminderWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderWrite"];
                };
            };
        };
    };
    v1_reminders_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_reminders_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedReminderWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedReminderWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedReminderWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderWrite"];
                };
            };
        };
    };
    v1_reminders_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderDetail"];
                };
            };
        };
    };
}
